version: '3.8'

services:
  frontend:
    container_name: ukfp-allocation-frontend
    image: ukfp-allocation-frontend:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - API_URL=http://ukfp-allocation-api:5000

  api:
    container_name: ukfp-allocation-api
    image: ukfp-allocation-api:latest
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - WORKER_API_URL=http://ukfp-allocation-worker-api:6000
      - REDIS_URL=redis://ukfp-allocation-redis:6379

  worker-api:
    container_name: ukfp-allocation-worker-api
    image: ukfp-allocation-worker-api:latest
    ports:
      - "6000:5000"
    depends_on:
      - rabbitmq
      - redis
    environment:
      - PORT=5000
      - REDIS_HOST=redis
      - RABBITMQ_HOST=rabbitmq

  worker-runner:
    container_name: ukfp-allocation-worker-runner
    image: ukfp-allocation-worker-runner:latest
    command: celery -A celery_app worker --loglevel=info
    ports:
      - "5000:7000"
    depends_on:
      - rabbitmq
      - redis

  rabbitmq:
    container_name: ukfp-allocation-rabbitmq
    image: rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    container_name: ukfp-allocation-redis
    image: "redis:alpine"
    ports:
      - "6379:6379"
